# Generated by Django 5.1.1 on 2024-11-02 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('cinema_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NowShowingMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_showing_movies', to='cinema.cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showing_movies', to='movies.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('now_showing_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_showing_scheduled_movies', to='cinema.nowshowingmovie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_identifier', models.CharField(default='', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('scheduled_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_tickets', to='cinema.scheduledmovie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
