# Generated by Django 5.1.1 on 2024-11-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_scheduledmovie_audience_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmovie",
            name="seats",
            field=models.JSONField(default=list),
        ),
    ]
