# Generated by Django 5.1.1 on 2024-11-20 05:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_scheduledmovie_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledmovie",
            name="now_showing_movie",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="scheduled_movie",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="user",
        ),
        migrations.DeleteModel(
            name="NowShowingMovie",
        ),
        migrations.DeleteModel(
            name="ScheduledMovie",
        ),
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
