# Generated by Django 5.1.1 on 2024-11-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0007_scheduledmovie_unique_scheduled_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmovie",
            name="price",
            field=models.FloatField(default=0),
        ),
    ]
