# Generated by Django 5.1.1 on 2024-11-24 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0008_scheduledmovie_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledmovie",
            name="price",
        ),
    ]
