# Generated by Django 5.1.1 on 2024-11-26 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0009_remove_scheduledmovie_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledmovie",
            name="seats",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="scheduled_movie",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="seat_identifier",
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_identifier", models.CharField(max_length=3)),
                (
                    "scheduled_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_seats",
                        to="cinema.scheduledmovie",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat",
            field=models.OneToOneField(
                default=django.utils.timezone.now,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ticket",
                to="cinema.seat",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["user", "is_active"], name="cinema_tick_user_id_5e8965_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(
                fields=["scheduled_movie", "seat_identifier"],
                name="cinema_seat_schedul_88a741_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("scheduled_movie", "seat_identifier"), name="unique_seat"
            ),
        ),
    ]
