# Generated by Django 5.1.1 on 2024-11-29 09:22

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0009_remove_scheduledmovie_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmovie",
            name="seats",
            field=models.JSONField(default=cinema.models.default_seat_matrix),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat_identifier",
            field=models.CharField(default="Z1", max_length=3),
        ),
    ]
