# Generated by Django 5.1.1 on 2024-11-26 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0010_remove_scheduledmovie_seats_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="scheduled_movie",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="seat",
        ),
        migrations.RemoveIndex(
            model_name="ticket",
            name="cinema_tick_user_id_5e8965_idx",
        ),
        migrations.DeleteModel(
            name="Seat",
        ),
    ]
