# Generated by Django 5.1.1 on 2024-11-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0011_remove_seat_scheduled_movie_remove_ticket_seat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledmovie",
            name="seats",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="scheduled_movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_tickets",
                to="cinema.scheduledmovie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="seat_identifier",
            field=models.CharField(default="Z1", max_length=3),
        ),
    ]
