# Generated by Django 5.1.1 on 2024-11-26 15:08

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0012_scheduledmovie_seats_ticket_scheduled_movie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduledmovie",
            name="seats",
            field=models.JSONField(default=cinema.models.default_seat_matrix),
        ),
    ]
