# Generated by Django 5.1.1 on 2024-11-27 02:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0013_alter_scheduledmovie_seats"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduledmovie",
            name="unique_scheduled_movie",
        ),
    ]
