# Generated by Django 5.1.1 on 2024-12-02 09:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(default="", upload_to=accounts.models.media_path),
        ),
    ]
