# Generated by Django 5.1.1 on 2024-12-02 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_profile_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="profile_picture",
            new_name="profile_pic",
        ),
    ]
