# Generated by Django 5.1.1 on 2024-12-02 10:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_profile_picture_customuser_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.FileField(default="", upload_to=accounts.models.media_path),
        ),
    ]
