# Generated by Django 5.1.1 on 2024-12-02 10:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_customuser_profile_pic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile_pic",
        ),
        migrations.AddField(
            model_name="customuser",
            name="picture",
            field=models.ImageField(default="", upload_to=accounts.models.media_path),
        ),
    ]
