# Generated by Django 5.1.1 on 2024-12-02 10:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_customuser_profile_pic_customuser_picture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="picture",
            new_name="profile",
        ),
    ]
