# Generated by Django 5.1.1 on 2024-12-02 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_rename_picture_customuser_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="profile",
        ),
    ]
