# Generated by Django 5.1.1 on 2024-10-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=50)),
                ('synopsis', models.TextField()),
                ('cast', models.TextField()),
                ('duration', models.DurationField()),
                ('movie_format', models.CharField(choices=[('2D', '2D'), ('3D', '3D')], default='2D', max_length=2)),
                ('movie_rating', models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance'), ('R-13', 'Restricted-13'), ('R-16', 'Restricted-16'), ('R-18', 'Restricted-18')], default='G', max_length=10)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
