# Generated by Django 5.1.1 on 2024-11-29 09:22

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_movie_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster_landscape",
            field=models.ImageField(default="", upload_to=movies.models.media_path),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_portrait",
            field=models.ImageField(default="", upload_to=movies.models.media_path),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster_trailer",
            field=models.FileField(default="", upload_to=movies.models.media_path),
        ),
    ]
